feat(scripts): update everforest colors

diff --git a/dotfile b/dotfile
--- a/dotfile
+++ b/dotfile
@@ -181,12 +181,59 @@ __dotfile_action() {
     exit 0
 }
 
+_check_dotfile_dependencies() {
+    dotfile=$1
+
+    # Load dependencies
+    if [ -f "$dotfiles_root/.depends/$dotfile" ]; then
+        . $dotfiles_root/.depends/$dotfile
+    fi
+
+    cmds="$dotfile $cmds"
+    for cmd in $cmds; do
+        if ! command -v $cmd >/dev/null 2>&1; then
+            error "The command '$cmd' is required $dotfile"
+            return 1
+        fi
+    done
+
+    return 0
+}
+
+_check_dependencies() {
+    shift
+
+    # List of dotfiles to act on
+    dotfiles="$@"
+    if [ -z "$dotfiles" ]; then
+        warn "selecting all dotfiles...\n"
+        dotfiles="$(__get_dotfiles)"
+    fi
+
+    # Act on dotfiles
+    for dotfile in $dotfiles; do
+        [ $dotfile = 'sysconf' ] && continue
+
+        _check_dotfile_dependencies "$(basename $dotfile)"
+
+        if [ $? -eq 0 ]; then
+            info "All $dotfile dependencies are satisfied."
+        fi
+    done
+
+    exit 0
+}
+
 
 [ $# -eq 0 ] && exit 1
 while [ $# -gt 0 ]; do
     case $1 in
         install | uninstall)
             __dotfile_action $@ # no return
+            ;;
+
+        check)
+            _check_dependencies $@ # no return
             ;;
 
         *)
